options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # 1. Installer et exécuter GitLeaks pour détecter les secrets
  - name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache curl wget
        wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O /usr/local/bin/gitleaks
        chmod +x /usr/local/bin/gitleaks
        /usr/local/bin/gitleaks detect --source app/src --exit-code 1

  # 2. Scanner les vulnérabilités avec Trivy
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        curl -sfL https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb focal main" > /etc/apt/sources.list.d/trivy.list
        apt-get update && apt-get install -y trivy
        trivy fs app/src

  # 3. Construire le binaire Go
  - name: "golang:1.21"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd app/src
        go build -o app-binary main.go

  # 4. Construire et Pousser l'image Docker dans Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build", "-t",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/go-repo/app-binary:latest",
      "-f", "app/src/Dockerfile",
      "app/src"
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "europe-west1-docker.pkg.dev/$PROJECT_ID/go-repo/app-binary:latest"
    ]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/go-repo/app-binary:latest"
